/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as OrigensRouteImport } from './routes/origens'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks.index'
import { Route as TasksNovaRouteImport } from './routes/tasks.nova'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigensRoute = OrigensRouteImport.update({
  id: '/origens',
  path: '/origens',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNovaRoute = TasksNovaRouteImport.update({
  id: '/tasks/nova',
  path: '/tasks/nova',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/origens': typeof OrigensRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tasks/nova': typeof TasksNovaRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/origens': typeof OrigensRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tasks/nova': typeof TasksNovaRoute
  '/tasks': typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/importacoes': typeof ImportacoesRoute
  '/origens': typeof OrigensRoute
  '/projetos': typeof ProjetosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tasks/nova': typeof TasksNovaRoute
  '/tasks/': typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/importacoes'
    | '/origens'
    | '/projetos'
    | '/relatorios'
    | '/tasks/nova'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/importacoes'
    | '/origens'
    | '/projetos'
    | '/relatorios'
    | '/tasks/nova'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/importacoes'
    | '/origens'
    | '/projetos'
    | '/relatorios'
    | '/tasks/nova'
    | '/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ImportacoesRoute: typeof ImportacoesRoute
  OrigensRoute: typeof OrigensRoute
  ProjetosRoute: typeof ProjetosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TasksNovaRoute: typeof TasksNovaRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origens': {
      id: '/origens'
      path: '/origens'
      fullPath: '/origens'
      preLoaderRoute: typeof OrigensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/nova': {
      id: '/tasks/nova'
      path: '/tasks/nova'
      fullPath: '/tasks/nova'
      preLoaderRoute: typeof TasksNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ImportacoesRoute: ImportacoesRoute,
  OrigensRoute: OrigensRoute,
  ProjetosRoute: ProjetosRoute,
  RelatoriosRoute: RelatoriosRoute,
  TasksNovaRoute: TasksNovaRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
